language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=countryx manage.py test countryx
after_success:
  - coveralls
