language: python
sudo: False
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=countryx manage.py test countryx
after_success:
  - coveralls
