# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0011_facilitator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
